server:
  port: 8811
spring:
  application:
    name: tide-service-demo
  datasource:
    url: jdbc:p6spy:mysql://localhost/cloud_music?serverTimezone=GMT%2B8
    username: root
    password: 1
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

