server:
  port: 8080
spring:
  application:
    name: tide-service-system
  datasource:
    url: jdbc:p6spy:mysql://47.94.147.204:3306/tide-system?serverTimezone=GMT%2B8
    username: root
    password: mysqlyyds
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 47.94.147.204
    port: 6379
    password: 123456
  mail:
    username: tideSender@163.com
    password: LTOJGHVAWFJGRCLR
    default-encoding: utf-8
    host: smtp.163.com
    port: 465
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          ssl:
            # 这里设为true时 端口号设为 465 设为false时 端口号设为994
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
#    username: 2559718264@qq.com
#    password: 1234qwerasdfzxc
#    default-encoding: utf-8
#    host: smtp.qq.com
#    port: 587
#    protocol: smtp
tide:
  security:
    tokenHeader: access-token
mybatis-plus:
  configuration:
    # 自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    #开启mybatis二级缓存
    cache-enabled: true
  global-config:
    db-config:
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type: AUTO
      # 逻辑未删除值
      logicNotDeleteValue: 0
      # 逻辑已删除值
      logicDeleteValue: 1
      key-generators:















#  boot:
#    admin:
#      client:
#        #这里配置admin server 的地址
#        url: http://47.94.147.204:2333
##开放端点用于SpringBoot Admin的监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


